version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: configstream-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: DynamicConfiguration
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - configstream-network

  # ConfigStream Web Application
  configstream-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: configstream-web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDB=mongodb://admin:password123@mongodb:27017/DynamicConfiguration?authSource=admin
    depends_on:
      - mongodb
    networks:
      - configstream-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  configstream-network:
    driver: bridge